### ISSUE TITLE
problem with chatting in the group

### ISSUE THREAD

**Issue by konradnash** [corncobb/telegram-instagram-engagement-bot#1]
Hi,
i am trying to use your bot but i have a issue.
i've installed it and ran it but when i am trying to send @username_ig during the drop session, the bot answers me "You may only give the bot commands in this chat🛑\nTo drop usernames, you must be in the group chat during round time" and it don't collect usernames. 
how can i solve this problem?
Many thanks in advance,
regards KM

**Comment by adeetyaa** [comment]
> Hi,
> i am trying to use your bot but i have a issue.
> i've installed it and ran it but when i am trying to send @username_ig during the drop session, the bot answers me "You may only give the bot commands in this chat🛑\nTo drop usernames, you must be in the group chat during round time" and it don't collect usernames.
> how can i solve this problem?
> Many thanks in advance,
> regards KM

Can you help me?
